### ISSUE TITLE
Non-interactive rebase

### ISSUE THREAD

**Issue by Mierdin** [githubteacher/advanced-may-2015#13]
If I choose to simply rebase without the -i flag for interactive, does this just use the "pick" option for all included commits?

In other words, we choose "interactive" because we want to do things like edit or reword, etc commits in the process of rebasing them onto the new branch. Something like that?

**Comment by githubstudent** [comment]
Yes, the benefit of rebase interactive is that it allows you to choose the commits you will rebase and make changes to those commits during the process. If you just want to rebase without making those changes you would exclude the -i flag!

**Comment by Mierdin** [comment]
So in a "standard" (if there is such a thing) use case like, I'm working in my own branch, and want to get updates from master, there's not really a big reason to do interactive, since I likely just want to take the commits as they are (lets say I'm not the one that made them). 

Let me know if that is too general, just want to get my head around what's commonplace.

**Comment by githubstudent** [comment]
yes, that is correct. Generally when you are just trying to pull updates from master then you would want all of the commits and there is no reason to use -i.
