### ISSUE TITLE
"Do not rebase public commits"

### ISSUE THREAD

**Issue by Mierdin** [githubteacher/advanced-may-2015#14]
I'm assuming this only applies to when you're changing commits that weren't yours. Obviously we will need to rebase commits on another branch into our branch so we stay caught up, and prevent future merge conflicts, yes?

**Comment by githubstudent** [comment]
It really applies to any commit that has been pushed to a repo that is shared. As a general rule, you should never rebase any commit that exists outside of your local repo. When you rebase you are essentially creating new commits so the history would no longer match the repos on anyone else's machine.

**Comment by Mierdin** [comment]
Understood - he just clarified this as well. Makes sense - in short, only rebase in your private repo before you push. Once you push, others may be building off of it and all bets are off. Obviously until you push this cannot happen, so rebase all you want.
