### ISSUE TITLE
Overriding default commands

### ISSUE THREAD

**Issue by Mierdin** [githubteacher/advanced-may-2015#4]
If I wanted to have "git log" do print oneline by default, could I do something like:

```
git config --global alias.log "git log --oneline"
```

I ran this and there was no error, but running "git log" didn't seem to print oneline style. Is there a way to do this, or is overriding existing commands silently prohibited?

**Comment by githubstudent** [comment]
We frequently set up something like this:

`git config --global alias.lol "log --oneline"`

And then to run it you would type:

`git lol`

**Comment by githubstudent** [comment]
@Mierdin ^^
