### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by DanielSiefert** [githubteacher/advanced-may-2015#5]
Is there any recommended daily/weekly/monthly maintenance tasks we should be running on our repo's.

**Comment by githubstudent** [comment]
@OfCourseITestedIt we do not have any recommended tasks for user level repos - however we do have some recommended audits for GitHub Enterprise instances. These are not covered in this class but I am happy to give you some additional info if this is what you are looking for!

**Comment by DanielSiefert** [comment]
Yes, if you could I'd appreciate it.

**Comment by githubteacher** [comment]
@OfCourseITestedIt Git actually runs maintenance tasks automatically and regularly in the background, with plumbing commands like `git gc` (garbage collection). It's rare for someone to have to perform manual maintenance of a repo. GitHub Enterprise also runs Git repo maintenance tasks in the background automatically, so you usually don't worry there, either.
