### ISSUE TITLE
Will we cover CI/CD tools today?

### ISSUE THREAD

**Issue by cheenpo** [githubteacher/advanced-may-2015#6]
yesterday, when a merge happened... the feedback of 'testing' (which I assume was some sort of unit testing, ci, jenkins, etc...). can we cover how that is possible/configurable. just high level, nothing crazy.

**Comment by githubstudent** [comment]
@cheenpo Patrick is planning to try to cover this today!

**Comment by githubteacher** [comment]
@cheenpo We'll cover CI briefly, primarily to show what's possible. Unfortunately, we don't have time to go through that in depth.

**Comment by cheenpo** [comment]
so its a web hook/trigger and then an api call from cd/travis/jenkins to put the result back into git?

**Comment by cheenpo** [comment]
you literally just explained it. cool beans.
now... github and gitlab... interchangeable there?

**Comment by cheenpo** [comment]
can i do the same thing on gitlab

**Comment by cheenpo** [comment]
no worries. thanks   :)  :+1:
