### ISSUE TITLE
Need Clarification

### ISSUE THREAD

**Issue by Mierdin** [githubteacher/advanced-may-2015#7]
So this is the "back-end" way of adding a file into staging as well as committing? I can see the steps, I'm just not clear on what it is that we're trying to accomplish. It would be nice if we could take a minute or two to talk about what we're doing before launching into the "how". I fear I'm wasting too much time sitting and contemplating "what" we're trying to do, while watching "how" we're doing it.

You know how cooking shows let you see the finished turkey before starting to clean the bird? Something like that would be useful.

**Comment by DanielSiefert** [comment]
I'm struggling with this as well.

**Comment by githubteacher** [comment]
@Mierdin @OfCourseITestedIt Thanks for the feedback! We'll cover this when returning from break.

**Comment by DanielSiefert** [comment]
I was thinking one more level up, so I understand that this is a breakdown of what's going on when we use an everyday command like a commit but would we find ourselves using this information if our repo somehow became corrupted?

**Comment by arjun911code** [comment]
:+1:

**Comment by Mierdin** [comment]
:+1: Thank you.
