### ISSUE TITLE
where can I find the video recording for this class

### ISSUE THREAD

**Issue by arjun911code** [githubteacher/advanced-may-2015#9]

**Comment by cheenpo** [comment]
jumping on this one... should we have already received the ones from the past couple of days?
just wanted to make sure I did not miss it if already sent.
thanks!

**Comment by githubstudent** [comment]
@arjun911code @cheenpo I thought I already responded to this one - sorry! 

We try to send these videos out within a couple of days of the end of the classes but they take some time to upload. I started uploading intermediate last night but it failed so I will try again today after class.
